// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static  FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeEhYuyDQNRdd56LFqAsQ4xCoJMm7YNxY',
    appId: '1:698031591265:web:6946b57ffebe3fff417f20',
    messagingSenderId: '698031591265',
    projectId: 'speso-6a5f0',
    //authDomain: 'speso-6a5f0.firebaseapp.com',
    storageBucket: 'speso-6a5f0.appspot.com',
  );

  static  FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7gb2j66EE1HNMlytAAu3FIRSt3X5_JXk',
    appId: '1:698031591265:android:2b7c9ac847a31671417f20',
    messagingSenderId: '698031591265',
    projectId: 'speso-6a5f0',
    storageBucket: 'speso-6a5f0.appspot.com',
  );

  static  FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtaXyOiRASjKTxeAKSBHclrIYKPnFPtww',
    appId: '1:698031591265:ios:9e2fd9746fab4b0f417f20',
    messagingSenderId: '698031591265',
    projectId: 'speso-6a5f0',
    storageBucket: 'speso-6a5f0.appspot.com',
    iosBundleId: 'com.example.spesoChatApp',
  );
}
